# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0b9bdd60d4e8413da2dc8ed157ea3f8938fa0a142f3107856a4682c8c33943a5b70b55710671805cf9476882dd6f121bd3da6fec5fc42eeaf4d5c92c786ad6f9

test:
  secret_key_base: 4359724105a8f42abcd1f156c449e810b0b88ce7c8469ab0dc1a98390f453ebcac392e9607f3e1ce3632e486c4123867568667d83e3efad67a65eedc4955f883

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
